spring:
  application:
    name: order-system

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"

server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/plain
info:
  application:
    groupId: '@project.groupId@'
    artifactId: '@project.artifactId@'
    version: '@project.version@'
chatgpt:
  api-key: ${API_KEY}
  model: gpt-3.5-turbo